"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import Image from "next/image";

import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";
import { Download, Share2, Mic2 } from "lucide-react";

interface SummaryRendererProps {
  summary: string;
}

const SummaryRenderer = ({ summary }: SummaryRendererProps) => {
  const parts = summary.split(/\*\*([^*]+)\*\*/);

  return (
    <>
      {parts.map((part, index) => {
        if (index % 2 === 1) {
          return (
            <span
              key={index}
              className="font-semibold bg-yellow-200 text-yellow-900 rounded px-1"
            >
              {part}
            </span>
          );
        }
        return <span key={index}>{part}</span>;
      })}
    </>
  );
};

const SharedSummaryPage = () => {
  const params = useParams();
  const { toast } = useToast();
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      const encoded = params.id as string;
      const decoded = decodeURIComponent(atob(encoded));
      setSummary(decoded);
    } catch {
      setError("Invalid or corrupted share link.");
    }
  }, [params.id]);

  const downloadPDF = () => {
    if (!summary) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;

    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Meeting Summary", pageWidth / 2, 30, { align: "center" });

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const lines = summary.split("\n");
    let y = 50;
    const lineHeight = 6;

    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      const isHeader = line.startsWith("**") || line.match(/^(Summary|Action Items|Key Points|Decisions|Next Steps):/i);

      if (isHeader) {
        doc.setFont("helvetica", "bold");
        const cleanLine = line.replace(/\*\*/g, "");
        const splitLines = doc.splitTextToSize(cleanLine, contentWidth);
        doc.text(splitLines, margin, y);
        y += splitLines.length * lineHeight + 2;
        doc.setFont("helvetica", "normal");
      } else {
        const cleanLine = line.replace(/\*\*/g, "");
        const splitLines = doc.splitTextToSize(cleanLine, contentWidth);
        doc.text(splitLines, margin, y);
        y += splitLines.length * lineHeight;
      }
    }

    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(128, 128, 128);
      doc.text("Generated by AudioScribe", pageWidth / 2, 285, { align: "center" });
      doc.setTextColor(0, 0, 0);
    }

    doc.save("shared-meeting-summary.pdf");

    toast({
      title: "PDF Downloaded",
      description: "Meeting summary has been saved as PDF.",
    });
  };

  const copyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    toast({
      title: "Link copied",
      description: "The shareable link has been copied to your clipboard.",
    });
  };

  if (error) {
    return (
      <section className="min-h-screen bg-dark-1 text-white flex items-center justify-center p-6">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4">Oops!</h1>
          <p className="text-sky-2">{error}</p>
        </div>
      </section>
    );
  }

  if (!summary) {
    return (
      <section className="min-h-screen bg-dark-1 text-white flex items-center justify-center p-6">
        <p className="text-sky-2">Loading...</p>
      </section>
    );
  }

  return (
    <section className="min-h-screen bg-dark-1 text-white">
      {/* Header */}
      <header className="border-b border-dark-3 bg-dark-1 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-1 rounded-lg">
              <Mic2 className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold">Shared via AudioScribe</h1>
              <p className="text-sky-2 text-sm">Meeting Summary</p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button
              onClick={downloadPDF}
              className="bg-green-600 hover:bg-green-700"
            >
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
            <Button
              onClick={copyLink}
              className="bg-blue-600 hover:bg-blue-700"
            >
              <Share2 className="w-4 h-4 mr-2" />
              Copy Link
            </Button>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-10">
        <div className="bg-dark-2 border border-dark-3 rounded-[14px] p-8">
          <div className="whitespace-pre-wrap text-base leading-relaxed text-sky-2">
            <SummaryRenderer summary={summary} />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-dark-3 bg-dark-1 px-6 py-6 mt-10">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-sky-2 text-sm">
            Shared via{" "}
            <span className="text-blue-1 font-semibold">AudioScribe</span>
          </p>
          <p className="text-sky-2 text-xs mt-2">
            AI-powered meeting summaries
          </p>
        </div>
      </footer>
    </section>
  );
};

export default SharedSummaryPage;
