"use client";

import { useState, useEffect } from "react";
import { jsPDF } from "jspdf";
import Image from "next/image";

import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  getSummaries,
  deleteSummary,
  SummaryEntry,
} from "@/lib/summaryHistory";
import { cn } from "@/lib/utils";
import { Download, Trash2, FileText, Calendar, ExternalLink } from "lucide-react";

interface SummaryRendererProps {
  summary: string;
}

const SummaryRenderer = ({ summary }: SummaryRendererProps) => {
  const parts = summary.split(/\*\*([^*]+)\*\*/);

  return (
    <>
      {parts.map((part, index) => {
        if (index % 2 === 1) {
          return (
            <span
              key={index}
              className="font-semibold bg-yellow-200 text-yellow-900 rounded px-1"
            >
              {part}
            </span>
          );
        }
        return <span key={index}>{part}</span>;
      })}
    </>
  );
};

const SummaryHistoryPage = () => {
  const { toast } = useToast();
  const [summaries, setSummaries] = useState<SummaryEntry[]>([]);
  const [selectedSummary, setSelectedSummary] = useState<SummaryEntry | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadSummaries();
  }, []);

  const loadSummaries = () => {
    const data = getSummaries();
    setSummaries(data);
    setIsLoading(false);
  };

  const handleDelete = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (confirm("Are you sure you want to delete this summary?")) {
      deleteSummary(id);
      loadSummaries();
      toast({
        title: "Summary deleted",
        description: "The summary has been removed from your history.",
      });
    }
  };

  const downloadPDF = (summary: SummaryEntry, e: React.MouseEvent) => {
    e.stopPropagation();

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;

    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Meeting Summary", pageWidth / 2, 30, { align: "center" });

    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(`${summary.title}`, pageWidth / 2, 45, { align: "center" });
    doc.text(`${summary.date}`, pageWidth / 2, 55, { align: "center" });

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const lines = summary.summary.split("\n");
    let y = 75;
    const lineHeight = 6;

    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      const isHeader = line.startsWith("**") || line.match(/^(Summary|Action Items|Key Points|Decisions|Next Steps):/i);

      if (isHeader) {
        doc.setFont("helvetica", "bold");
        const cleanLine = line.replace(/\*\*/g, "");
        const splitLines = doc.splitTextToSize(cleanLine, contentWidth);
        doc.text(splitLines, margin, y);
        y += splitLines.length * lineHeight + 2;
        doc.setFont("helvetica", "normal");
      } else {
        const cleanLine = line.replace(/\*\*/g, "");
        const splitLines = doc.splitTextToSize(cleanLine, contentWidth);
        doc.text(splitLines, margin, y);
        y += splitLines.length * lineHeight;
      }
    }

    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(128, 128, 128);
      doc.text("Generated by AudioScribe", pageWidth / 2, 285, { align: "center" });
      doc.setTextColor(0, 0, 0);
    }

    const dateStr = new Date().toISOString().split("T")[0];
    doc.save(`meeting-summary-${dateStr}.pdf`);

    toast({
      title: "PDF Downloaded",
      description: "Meeting summary has been saved as PDF.",
    });
  };

  const openSummary = (summary: SummaryEntry) => {
    setSelectedSummary(summary);
    setIsDialogOpen(true);
  };

  if (isLoading) {
    return (
      <section className="flex size-full flex-col gap-10 text-white p-6">
        <h1 className="text-3xl font-bold">Summary History</h1>
        <div className="flex items-center justify-center h-64">
          <p className="text-sky-2">Loading...</p>
        </div>
      </section>
    );
  }

  return (
    <section className="flex size-full flex-col gap-10 text-white p-6">
      <h1 className="text-3xl font-bold">Summary History</h1>

      {summaries.length === 0 ? (
        <div className="flex flex-col items-center justify-center h-64 gap-4">
          <FileText className="w-16 h-16 text-sky-2 opacity-50" />
          <p className="text-sky-2 text-lg">No summaries yet.</p>
          <p className="text-sky-2 text-sm">
            Generate summaries from your recordings to see them here.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {summaries.map((summary) => (
            <div
              key={summary.id}
              onClick={() => openSummary(summary)}
              className="bg-dark-1 border border-dark-3 rounded-[14px] p-6 cursor-pointer hover:border-blue-1 transition-colors"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2 text-sky-2">
                  <Calendar className="w-4 h-4" />
                  <span className="text-sm">{summary.date}</span>
                </div>
                <div className="flex gap-2">
                  <Button
                    onClick={(e) => downloadPDF(summary, e)}
                    className="bg-green-600 hover:bg-green-700 p-2 h-8 w-8"
                    size="sm"
                  >
                    <Download className="w-4 h-4" />
                  </Button>
                  <Button
                    onClick={(e) => handleDelete(summary.id, e)}
                    className="bg-red-600 hover:bg-red-700 p-2 h-8 w-8"
                    size="sm"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>

              <h3 className="text-xl font-semibold mb-2 line-clamp-1">{summary.title}</h3>

              <p className="text-sky-2 text-sm line-clamp-3">
                {summary.summary.substring(0, 100)}...
              </p>

              <div className="mt-4 flex items-center text-blue-1 text-sm">
                <ExternalLink className="w-4 h-4 mr-1" />
                Click to view full summary
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Summary Detail Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto bg-dark-1 border-dark-3 text-white">
          {selectedSummary && (
            <>
              <DialogHeader>
                <DialogTitle className="text-2xl font-bold text-white">
                  {selectedSummary.title}
                </DialogTitle>
                <DialogDescription className="text-sky-1">
                  {selectedSummary.date}
                </DialogDescription>
              </DialogHeader>

              <div className="flex gap-2 mt-4">
                <Button
                  onClick={() => downloadPDF(selectedSummary, {
                    stopPropagation: () => {},
                  } as React.MouseEvent)}
                  className="bg-green-600 hover:bg-green-700"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </Button>
              </div>

              <div className="mt-4 whitespace-pre-wrap text-base leading-relaxed text-sky-2">
                <SummaryRenderer summary={selectedSummary.summary} />
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </section>
  );
};

export default SummaryHistoryPage;
